-- Seed data

-- 1. Card Types
INSERT INTO public.card_types (code, name, description)
VALUES ('basic-front-back', 'Basic Front/Back', 'Standard flashcard with a front and back side.')
ON CONFLICT (code) DO NOTHING;

-- 2. Knowledge (100 items)
INSERT INTO public.knowledge (name, description, metadata) VALUES ('abandon', '放弃；抛弃', '{"pos": "v.", "level": "B2", "exampleSentence": "Don''t abandon your dreams.", "selfExaminePrompt": "When might someone abandon a project?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('abstract', '抽象的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Abstract art is difficult to understand.", "selfExaminePrompt": "What is the difference between abstract and concrete?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('abuse', '滥用；虐待', '{"pos": "n.", "level": "B2", "exampleSentence": "Drug abuse is a serious problem.", "selfExaminePrompt": "What types of abuse should we prevent?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('acceptable', '可接受的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Your work is acceptable but not excellent.", "selfExaminePrompt": "What makes behavior acceptable?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('accompany', '陪伴；伴随', '{"pos": "v.", "level": "B2", "exampleSentence": "I will accompany you to the hospital.", "selfExaminePrompt": "Who do you like to accompany you?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('accomplish', '完成；实现', '{"pos": "v.", "level": "B2", "exampleSentence": "She accomplished her goal of learning English.", "selfExaminePrompt": "What have you accomplished this year?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('accurate', '准确的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Please give me accurate information.", "selfExaminePrompt": "Why is accuracy important in work?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('accurately', '准确地', '{"pos": "adv.", "level": "B2", "exampleSentence": "He described the event accurately.", "selfExaminePrompt": "How can you speak more accurately?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('accuse', '指控；指责', '{"pos": "v.", "level": "B2", "exampleSentence": "They accused him of stealing.", "selfExaminePrompt": "What should you do when falsely accused?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('acquire', '获得；习得', '{"pos": "v.", "level": "B2", "exampleSentence": "Students acquire knowledge through study.", "selfExaminePrompt": "What skills do you want to acquire?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('actively', '积极地', '{"pos": "adv.", "level": "B2", "exampleSentence": "She participates actively in class.", "selfExaminePrompt": "How can you actively improve your English?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('adapt', '适应；改编', '{"pos": "v.", "level": "B2", "exampleSentence": "Animals adapt to their environment.", "selfExaminePrompt": "How do you adapt to new situations?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('adequate', '足够的；适当的', '{"pos": "adj.", "level": "B2", "exampleSentence": "We need adequate funding for the project.", "selfExaminePrompt": "What is adequate preparation for an exam?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('adjacent', '邻近的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The hotel is adjacent to the airport.", "selfExaminePrompt": "What buildings are adjacent to your school?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('adjust', '调整；适应', '{"pos": "v.", "level": "B2", "exampleSentence": "Please adjust the temperature.", "selfExaminePrompt": "What do you need to adjust in your life?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('administration', '管理；行政', '{"pos": "n.", "level": "B2", "exampleSentence": "The school administration made new rules.", "selfExaminePrompt": "What does administration mean in government?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('administrative', '管理的；行政的', '{"pos": "adj.", "level": "B2", "exampleSentence": "She works in an administrative position.", "selfExaminePrompt": "What administrative tasks do you do?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('adopt', '采用；收养', '{"pos": "v.", "level": "B2", "exampleSentence": "They decided to adopt a child.", "selfExaminePrompt": "What new methods should schools adopt?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('advocate', '提倡；支持', '{"pos": "v.", "level": "B2", "exampleSentence": "I advocate for environmental protection.", "selfExaminePrompt": "What causes do you advocate for?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('affair', '事务；事件', '{"pos": "n.", "level": "B2", "exampleSentence": "This is a private affair.", "selfExaminePrompt": "What public affairs concern you?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('agricultural', '农业的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Agricultural products are exported worldwide.", "selfExaminePrompt": "What agricultural activities happen in your region?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('agriculture', '农业', '{"pos": "n.", "level": "B2", "exampleSentence": "Agriculture is important for food production.", "selfExaminePrompt": "How has agriculture changed over time?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('aid', '援助；帮助', '{"pos": "n.", "level": "B2", "exampleSentence": "The country received foreign aid.", "selfExaminePrompt": "When do countries need international aid?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('aircraft', '飞机', '{"pos": "n.", "level": "B2", "exampleSentence": "Military aircraft flew overhead.", "selfExaminePrompt": "What types of aircraft do you know?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('alien', '外国的；陌生的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The customs seemed alien to him.", "selfExaminePrompt": "What alien concepts are hard to understand?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('allocate', '分配；拨给', '{"pos": "v.", "level": "B2", "exampleSentence": "We need to allocate resources wisely.", "selfExaminePrompt": "How should schools allocate their budget?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('ally', '盟友；同盟', '{"pos": "n.", "level": "B2", "exampleSentence": "France is a traditional ally of the US.", "selfExaminePrompt": "Who is your closest ally at work?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('alter', '改变；修改', '{"pos": "v.", "level": "B2", "exampleSentence": "Climate change will alter weather patterns.", "selfExaminePrompt": "What would you like to alter about your life?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('altogether', '完全地；总共', '{"pos": "adv.", "level": "B2", "exampleSentence": "The project cost $50,000 altogether.", "selfExaminePrompt": "What should be banned altogether?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('amend', '修正；修改', '{"pos": "v.", "level": "B2", "exampleSentence": "Parliament voted to amend the law.", "selfExaminePrompt": "What laws need to be amended?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('angel', '天使', '{"pos": "n.", "level": "B2", "exampleSentence": "She looks like an angel.", "selfExaminePrompt": "What makes someone seem like an angel?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anger', '愤怒', '{"pos": "n.", "level": "B2", "exampleSentence": "He couldn''t control his anger.", "selfExaminePrompt": "How do you manage your anger?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anniversary', '周年纪念', '{"pos": "n.", "level": "B2", "exampleSentence": "They celebrated their wedding anniversary.", "selfExaminePrompt": "What anniversaries do you celebrate?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('annual', '年度的；每年的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The annual meeting is next week.", "selfExaminePrompt": "What annual events do you attend?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('annually', '每年地', '{"pos": "adv.", "level": "B2", "exampleSentence": "The festival is held annually.", "selfExaminePrompt": "What do you do annually on your birthday?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anonymous', '匿名的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The donor wished to remain anonymous.", "selfExaminePrompt": "When is anonymous feedback useful?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anticipate', '预期；期待', '{"pos": "v.", "level": "B2", "exampleSentence": "I anticipate problems with the plan.", "selfExaminePrompt": "What do you anticipate for next year?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anxiety', '焦虑；担心', '{"pos": "n.", "level": "B2", "exampleSentence": "Exam anxiety affects many students.", "selfExaminePrompt": "What causes you the most anxiety?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('anxious', '焦虑的；急切的', '{"pos": "adj.", "level": "B2", "exampleSentence": "She was anxious about the results.", "selfExaminePrompt": "When do you feel most anxious?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('appeal', '呼吁；吸引', '{"pos": "v.", "level": "B2", "exampleSentence": "The charity appealed for donations.", "selfExaminePrompt": "What causes appeal to you?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('applicant', '申请人', '{"pos": "n.", "level": "B2", "exampleSentence": "The job applicant was well qualified.", "selfExaminePrompt": "What makes a strong applicant?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('appoint', '任命；约定', '{"pos": "v.", "level": "B2", "exampleSentence": "The board will appoint a new director.", "selfExaminePrompt": "Who has the power to appoint leaders?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('approach', '方法；途径', '{"pos": "n.", "level": "B2", "exampleSentence": "We need a new approach to this problem.", "selfExaminePrompt": "What approach works best for learning?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('appropriate', '合适的；恰当的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Choose appropriate clothing for the interview.", "selfExaminePrompt": "What is appropriate behavior in class?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('approval', '批准；赞成', '{"pos": "n.", "level": "B2", "exampleSentence": "The project needs government approval.", "selfExaminePrompt": "Whose approval do you value most?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('approve', '批准；赞成', '{"pos": "v.", "level": "B2", "exampleSentence": "Parents must approve the field trip.", "selfExaminePrompt": "What decisions do you need to approve?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('arise', '出现；产生', '{"pos": "v.", "level": "B2", "exampleSentence": "Problems may arise during construction.", "selfExaminePrompt": "What problems arise from poor planning?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('armed', '武装的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Armed guards protected the building.", "selfExaminePrompt": "What places have armed security?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('artificial', '人工的；人造的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Artificial intelligence is advancing rapidly.", "selfExaminePrompt": "What artificial products do you use daily?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('artistic', '艺术的；有艺术性的', '{"pos": "adj.", "level": "B2", "exampleSentence": "She has great artistic talent.", "selfExaminePrompt": "What artistic skills do you have?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('aside', '在一边；除...之外', '{"pos": "adv.", "level": "B2", "exampleSentence": "Put your phone aside during class.", "selfExaminePrompt": "What should you set aside for the future?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('aspect', '方面；层面', '{"pos": "n.", "level": "B2", "exampleSentence": "Consider every aspect of the problem.", "selfExaminePrompt": "What aspect of English is hardest?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assault', '攻击；袭击', '{"pos": "n.", "level": "B2", "exampleSentence": "The victim reported the assault to police.", "selfExaminePrompt": "How can we prevent assault?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assemble', '聚集；组装', '{"pos": "v.", "level": "B2", "exampleSentence": "Students assembled in the auditorium.", "selfExaminePrompt": "When do people assemble for meetings?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assembly', '集会；装配', '{"pos": "n.", "level": "B2", "exampleSentence": "The school held a special assembly.", "selfExaminePrompt": "What assemblies do you attend?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assess', '评估；评价', '{"pos": "v.", "level": "B2", "exampleSentence": "Teachers assess student performance.", "selfExaminePrompt": "How do you assess your own progress?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assessment', '评估；评价', '{"pos": "n.", "level": "B2", "exampleSentence": "The assessment showed positive results.", "selfExaminePrompt": "What assessment methods are most fair?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('asset', '资产；有价值的东西', '{"pos": "n.", "level": "B2", "exampleSentence": "Good health is a valuable asset.", "selfExaminePrompt": "What is your greatest personal asset?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('associate', '联想；关联', '{"pos": "v.", "level": "B2", "exampleSentence": "I associate this song with summer.", "selfExaminePrompt": "What do you associate with happiness?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('association', '协会；联想', '{"pos": "n.", "level": "B2", "exampleSentence": "She joined the teachers'' association.", "selfExaminePrompt": "What associations do you belong to?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assume', '假设；承担', '{"pos": "v.", "level": "B2", "exampleSentence": "I assume you know the answer.", "selfExaminePrompt": "What do you assume about people?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assumption', '假设；假定', '{"pos": "n.", "level": "B2", "exampleSentence": "That assumption proved to be wrong.", "selfExaminePrompt": "What assumptions should we question?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('assure', '保证；使确信', '{"pos": "v.", "level": "B2", "exampleSentence": "I can assure you it''s safe.", "selfExaminePrompt": "How do you assure someone who is worried?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('athletic', '运动的；体格健壮的', '{"pos": "adj.", "level": "B2", "exampleSentence": "He has an athletic build.", "selfExaminePrompt": "What athletic activities do you enjoy?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('attempt', '尝试；企图', '{"pos": "n.", "level": "B2", "exampleSentence": "This is my first attempt at cooking.", "selfExaminePrompt": "What was your best attempt at something difficult?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('attendance', '出席；参加', '{"pos": "n.", "level": "B2", "exampleSentence": "Class attendance is mandatory.", "selfExaminePrompt": "How is attendance tracked at your school?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('attorney', '律师', '{"pos": "n.", "level": "B2", "exampleSentence": "The attorney represented the defendant.", "selfExaminePrompt": "When do people need an attorney?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('attribute', '属性；特征', '{"pos": "n.", "level": "B2", "exampleSentence": "Patience is an important attribute.", "selfExaminePrompt": "What attributes make a good leader?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('auto', '汽车', '{"pos": "n.", "level": "B2", "exampleSentence": "He works in the auto industry.", "selfExaminePrompt": "What auto features are most important?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('automatic', '自动的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The door has an automatic lock.", "selfExaminePrompt": "What automatic systems do you use?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('automatically', '自动地', '{"pos": "adv.", "level": "B2", "exampleSentence": "The lights turn on automatically.", "selfExaminePrompt": "What happens automatically in your daily routine?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('automobile', '汽车', '{"pos": "n.", "level": "B2", "exampleSentence": "The automobile industry is changing.", "selfExaminePrompt": "How has the automobile impacted society?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('backup', '备份；后备', '{"pos": "n.", "level": "B2", "exampleSentence": "Always keep a backup of important files.", "selfExaminePrompt": "What should you always have a backup for?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bare', '光秃的；空的', '{"pos": "adj.", "level": "B2", "exampleSentence": "The tree branches were bare.", "selfExaminePrompt": "What looks bare in winter?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('barely', '几乎不；勉强', '{"pos": "adv.", "level": "B2", "exampleSentence": "I can barely see in this light.", "selfExaminePrompt": "What can you barely manage to do?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bargain', '便宜货；协议', '{"pos": "n.", "level": "B2", "exampleSentence": "That shirt was a real bargain.", "selfExaminePrompt": "Where do you find the best bargains?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('barrier', '障碍；屏障', '{"pos": "n.", "level": "B2", "exampleSentence": "Language can be a barrier to communication.", "selfExaminePrompt": "What barriers prevent you from success?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bear', '承受；忍受', '{"pos": "v.", "level": "B2", "exampleSentence": "I can''t bear this pain anymore.", "selfExaminePrompt": "What is difficult to bear in life?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('behalf', '代表；利益', '{"pos": "n.", "level": "B2", "exampleSentence": "I''m calling on behalf of my boss.", "selfExaminePrompt": "Who do you speak on behalf of?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('behavior', '行为；举止', '{"pos": "n.", "level": "B2", "exampleSentence": "His behavior was inappropriate.", "selfExaminePrompt": "What behavior do you find annoying?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('being', '存在；生物', '{"pos": "n.", "level": "B2", "exampleSentence": "Every living being deserves respect.", "selfExaminePrompt": "What kind of being are humans?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bench', '长凳；工作台', '{"pos": "n.", "level": "B2", "exampleSentence": "They sat on a park bench.", "selfExaminePrompt": "Where do you find benches?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('beside', '在...旁边', '{"pos": "prep.", "level": "B2", "exampleSentence": "She sat beside me in class.", "selfExaminePrompt": "Who sits beside you at dinner?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bet', '打赌；确信', '{"pos": "v.", "level": "B2", "exampleSentence": "I bet it will rain tomorrow.", "selfExaminePrompt": "What would you bet money on?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('beyond', '超出；在...之外', '{"pos": "prep.", "level": "B2", "exampleSentence": "The mountain is beyond those trees.", "selfExaminePrompt": "What is beyond your comfort zone?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bid', '出价；投标', '{"pos": "n.", "level": "B2", "exampleSentence": "His bid for the house was accepted.", "selfExaminePrompt": "What would you make a bid on?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('bind', '绑定；约束', '{"pos": "v.", "level": "B2", "exampleSentence": "The contract will bind both parties.", "selfExaminePrompt": "What binds people together?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('biological', '生物的；生物学的', '{"pos": "adj.", "level": "B2", "exampleSentence": "She studies biological processes.", "selfExaminePrompt": "What biological factors affect health?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('blade', '刀片；叶片', '{"pos": "n.", "level": "B2", "exampleSentence": "The knife blade is very sharp.", "selfExaminePrompt": "What objects have blades?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('blame', '责备；归咎于', '{"pos": "v.", "level": "B2", "exampleSentence": "Don''t blame me for the mistake.", "selfExaminePrompt": "Who do people often blame unfairly?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('boom', '繁荣；巨响', '{"pos": "n.", "level": "B2", "exampleSentence": "The economy experienced a boom.", "selfExaminePrompt": "What industries are experiencing a boom?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('breast', '胸部；乳房', '{"pos": "n.", "level": "B2", "exampleSentence": "Breast cancer affects many women.", "selfExaminePrompt": "What health issues affect the breast?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('brief', '简短的；简洁的', '{"pos": "adj.", "level": "B2", "exampleSentence": "Please give a brief summary.", "selfExaminePrompt": "When is brief communication better?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('briefly', '简短地；简洁地', '{"pos": "adv.", "level": "B2", "exampleSentence": "Let me explain this briefly.", "selfExaminePrompt": "What should be explained briefly?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('broad', '宽阔的；广泛的', '{"pos": "adj.", "level": "B2", "exampleSentence": "He has broad shoulders.", "selfExaminePrompt": "What gives you a broad perspective?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('broadcast', '广播；播放', '{"pos": "v.", "level": "B2", "exampleSentence": "The game will be broadcast live.", "selfExaminePrompt": "What programs do you like to watch broadcast?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('buck', '美元；雄鹿', '{"pos": "n.", "level": "B2", "exampleSentence": "The coffee costs five bucks.", "selfExaminePrompt": "How many bucks do you spend daily?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('budget', '预算；预算案', '{"pos": "n.", "level": "B2", "exampleSentence": "We need to stay within budget.", "selfExaminePrompt": "How do you manage your monthly budget?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('buyer', '买家；采购员', '{"pos": "n.", "level": "B2", "exampleSentence": "The buyer inspected the house.", "selfExaminePrompt": "What makes a serious buyer?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.knowledge (name, description, metadata) VALUES ('cable', '电缆；有线电视', '{"pos": "n.", "level": "B2", "exampleSentence": "The internet cable is broken.", "selfExaminePrompt": "What devices use cables?", "theme": "", "imageName": null}') ON CONFLICT (name) DO NOTHING;

-- 3. Users
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    recovery_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'authenticated',
    'authenticated',
    'boymgl@qq.com',
    extensions.crypt('password123', extensions.gen_salt('bf')),
    now(),
    now(),
    now(),
    '{"provider": "email", "providers": ["email"], "role": "operator"}',
    '{}',
    now(),
    now(),
    '',
    '',
    '',
    ''
) ON CONFLICT (id) DO NOTHING;

-- 4. Accounts
INSERT INTO public.accounts (id, username)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'boymgl'
) ON CONFLICT (id) DO NOTHING;
