-- Migration: Add push_subscriptions table
-- Date: 2026-01-02

CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "endpoint" text NOT NULL UNIQUE,
    "keys" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";

-- RLS
ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can manage their own subscriptions
CREATE POLICY "Users can manage their own subscriptions" ON "public"."push_subscriptions"
FOR ALL USING ((select auth.uid()) = user_id);
