-- Migration: Add NPS ratings and referral tracking
-- Date: 2026-02-22

-- 1. NPS ratings table
CREATE TABLE IF NOT EXISTS public.nps_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id uuid REFERENCES public.accounts(id) ON DELETE SET NULL,
  score integer NOT NULL CHECK (score >= 0 AND score <= 10),
  comment text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_nps_ratings_account ON public.nps_ratings(account_id);
CREATE INDEX idx_nps_ratings_created ON public.nps_ratings(created_at);

ALTER TABLE public.nps_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own ratings" ON public.nps_ratings
  FOR INSERT WITH CHECK ((select auth.uid()) = account_id);

CREATE POLICY "Users can view own ratings" ON public.nps_ratings
  FOR SELECT USING ((select auth.uid()) = account_id);

CREATE POLICY "Operators can view all ratings" ON public.nps_ratings
  FOR SELECT USING (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'operator');

-- 2. Referrals table
CREATE TABLE IF NOT EXISTS public.referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  referred_id uuid REFERENCES public.accounts(id) ON DELETE SET NULL,
  referral_code text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'converted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  converted_at timestamptz
);

CREATE INDEX idx_referrals_referrer ON public.referrals(referrer_id);
CREATE INDEX idx_referrals_code ON public.referrals(referral_code);
CREATE INDEX idx_referrals_referred ON public.referrals(referred_id);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own referrals" ON public.referrals
  FOR SELECT USING ((select auth.uid()) = referrer_id);

CREATE POLICY "Operators can view all referrals" ON public.referrals
  FOR SELECT USING (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'operator');

-- Add referral_code to accounts for easy lookup
ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS referral_code text UNIQUE;

-- Add referred_by to accounts to track who invited them
ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS referred_by uuid REFERENCES public.accounts(id);

-- 3. Dashboard RPCs for NPS and K-factor

-- NPS score calculation
CREATE OR REPLACE FUNCTION public.get_dashboard_nps()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total bigint;
  v_promoters bigint;
  v_detractors bigint;
  v_nps numeric;
  v_avg_score numeric;
BEGIN
  SELECT count(*) INTO v_total FROM nps_ratings
  WHERE created_at >= now() - interval '90 days';

  IF v_total = 0 THEN
    RETURN json_build_object('nps', 0, 'total', 0, 'avgScore', 0,
      'promoters', 0, 'passives', 0, 'detractors', 0);
  END IF;

  SELECT count(*) INTO v_promoters FROM nps_ratings
  WHERE score >= 9 AND created_at >= now() - interval '90 days';

  SELECT count(*) INTO v_detractors FROM nps_ratings
  WHERE score <= 6 AND created_at >= now() - interval '90 days';

  v_nps := round(((v_promoters - v_detractors)::numeric / v_total * 100), 1);

  SELECT round(avg(score), 1) INTO v_avg_score FROM nps_ratings
  WHERE created_at >= now() - interval '90 days';

  RETURN json_build_object(
    'nps', v_nps,
    'total', v_total,
    'avgScore', v_avg_score,
    'promoters', v_promoters,
    'passives', v_total - v_promoters - v_detractors,
    'detractors', v_detractors
  );
END;
$$;

ALTER FUNCTION public.get_dashboard_nps() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.get_dashboard_nps() TO service_role;

-- K-factor calculation
CREATE OR REPLACE FUNCTION public.get_dashboard_kfactor()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_users bigint;
  v_users_who_invited bigint;
  v_total_invites bigint;
  v_converted_invites bigint;
  v_invite_rate numeric;
  v_conversion_rate numeric;
  v_kfactor numeric;
BEGIN
  SELECT count(*) INTO v_total_users FROM accounts;

  SELECT count(DISTINCT referrer_id) INTO v_users_who_invited FROM referrals;

  SELECT count(*) INTO v_total_invites FROM referrals;

  SELECT count(*) INTO v_converted_invites FROM referrals WHERE status = 'converted';

  v_invite_rate := CASE WHEN v_total_users > 0
    THEN v_total_invites::numeric / v_total_users
    ELSE 0 END;

  v_conversion_rate := CASE WHEN v_total_invites > 0
    THEN v_converted_invites::numeric / v_total_invites
    ELSE 0 END;

  -- K-factor = invites per user × conversion rate
  v_kfactor := round(v_invite_rate * v_conversion_rate, 3);

  RETURN json_build_object(
    'kfactor', v_kfactor,
    'totalUsers', v_total_users,
    'usersWhoInvited', v_users_who_invited,
    'totalInvites', v_total_invites,
    'convertedInvites', v_converted_invites,
    'inviteRate', round(v_invite_rate, 3),
    'conversionRate', round(v_conversion_rate * 100, 1)
  );
END;
$$;

ALTER FUNCTION public.get_dashboard_kfactor() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.get_dashboard_kfactor() TO service_role;
