#!/usr/bin/env node

/**
 * Script to generate favicon and app icons from pwa-icon-108.png
 * Requires: sharp (npm install sharp)
 * 
 * Usage: node scripts/generate-icons.mjs
 * 
 * All icons are generated by scaling pwa-icon-108.png to the required sizes.
 */

import sharp from 'sharp';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

const iconSizes = [
  { name: 'favicon.png', size: 32 },
  { name: 'icon.png', size: 512 },
  { name: 'apple-icon.png', size: 180 },
  { name: 'icon-192.png', size: 192 },
  { name: 'icon-512.png', size: 512 },
];

async function generateIcons() {
  try {
    const sourcePath = join(rootDir, 'public', 'pwa-icon-108.png');
    
    for (const icon of iconSizes) {
      const outputPath = join(rootDir, 'public', icon.name);
      
      if (icon.name === 'favicon.ico') {
        // Generate PNG first, then can be converted to ICO
        const pngPath = outputPath.replace('.ico', '.png');
        await sharp(sourcePath)
          .resize(icon.size, icon.size)
          .png()
          .toFile(pngPath);
        console.log(`✓ Generated ${icon.name.replace('.ico', '.png')} (use as favicon)`);
      } else {
        await sharp(sourcePath)
          .resize(icon.size, icon.size)
          .png()
          .toFile(outputPath);
        console.log(`✓ Generated ${icon.name}`);
      }
    }
    
    console.log('\nNote: For favicon.ico, convert favicon.png to ICO format using an online tool');
    console.log('or use: npm install -g to-ico && to-ico public/favicon.png -o public/favicon.ico');
  } catch (error) {
    console.error('Error generating icons:', error.message);
    console.log('\nNote: Install sharp first: npm install sharp');
    process.exit(1);
  }
}

generateIcons();
