/**
 * Miniprogram configuration
 * Auto-generated by build script - DO NOT EDIT MANUALLY
 * Generated at: 2026-02-16T12:01:06.054Z
 */

export const CONFIG = {
  // API base URL (from NEXT_PUBLIC_APP_ORIGIN)
  API_BASE_URL: 'https://preview.iamsmart.top',
  
  // App ID (from WECHAT_MINIPROGRAM_APP_ID)
  APP_ID: 'wxe3af85edd5fae27f',
} as const;
