#!/usr/bin/env node

/**
 * Script to generate logo.png from pwa-icon-108.png
 * Requires: sharp (npm install sharp)
 * 
 * Usage: node scripts/generate-logo.mjs
 * 
 * Logo is generated by scaling pwa-icon-108.png to 512x512px.
 */

import sharp from 'sharp';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

async function generateLogo() {
  try {
    const sourcePath = join(rootDir, 'public', 'pwa-icon-108.png');
    const outputPath = join(rootDir, 'public', 'logo.png');
    
    await sharp(sourcePath)
      .resize(512, 512)
      .png()
      .toFile(outputPath);
    
    console.log(`✓ Generated ${outputPath} from pwa-icon-108.png`);
  } catch (error) {
    console.error('Error generating logo:', error.message);
    console.log('\nNote: Install sharp first: npm install sharp');
    process.exit(1);
  }
}

generateLogo();
