/**
 * Supabase Edge Function: send-sms (Auth Hook)
 *
 * This function is called by Supabase GoTrue (Auth) via the `send_sms` hook
 * whenever an SMS OTP needs to be sent (sign-in, MFA, etc.).
 *
 * It forwards the OTP to the user's phone via Alibaba Cloud SMS Verify Service
 * (短信认证服务), which requires no custom signature/template approval.
 *
 * Required environment variables (set in Supabase Dashboard > Edge Functions > Secrets):
 *   ALIYUN_SMS_ACCESS_KEY_ID     - Alibaba Cloud AccessKey ID
 *   ALIYUN_SMS_ACCESS_KEY_SECRET - Alibaba Cloud AccessKey Secret
 *   ALIYUN_SMS_SIGN_NAME         - SMS signature name (系统赠送签名)
 *   ALIYUN_SMS_TEMPLATE_CODE     - SMS template code (系统赠送模板CODE)
 *   SUPABASE_AUTH_HOOK_SECRET    - Shared secret for webhook verification (optional)
 *
 * Reference:
 *   - Supabase SMS Hook: https://supabase.com/docs/guides/auth/phone-login/phone-hook
 *   - Alibaba Cloud SMS Verify: https://help.aliyun.com/zh/pnvs/developer-reference/api-dypnsapi-2017-05-25-sendsmsverifycode
 */

import { createHmac } from "node:crypto";

// ─── Types ───────────────────────────────────────────────────────────────────

interface SendSmsHookPayload {
  user: {
    phone: string;
  };
  sms: {
    otp: string;
  };
}

interface SendSmsVerifyCodeResponse {
  Code: string;
  Message: string;
  RequestId: string;
  Success: boolean;
  Model?: {
    VerifyCode?: string;
    RequestId?: string;
    BizId?: string;
    OutId?: string;
  };
}

// ─── Alibaba Cloud SMS Signing (v1 Signature) ───────────────────────────────

function percentEncode(value: string): string {
  return encodeURIComponent(value)
    .replace(/\+/g, "%2B")
    .replace(/\*/g, "%2A")
    .replace(/%7E/g, "~");
}

function generateSignature(
  params: Record<string, string>,
  accessKeySecret: string
): string {
  const sortedKeys = Object.keys(params).sort();
  const canonicalized = sortedKeys
    .map((key) => `${percentEncode(key)}=${percentEncode(params[key])}`)
    .join("&");

  const stringToSign = `POST&${percentEncode("/")}&${percentEncode(canonicalized)}`;

  const hmac = createHmac("sha1", `${accessKeySecret}&`);
  hmac.update(stringToSign);
  return hmac.digest("base64");
}

function generateNonce(): string {
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return Array.from(array, (b) => b.toString(16).padStart(2, "0")).join("");
}

// ─── Send SMS via Alibaba Cloud SMS Verify Service ───────────────────────────

async function sendAliyunSmsVerifyCode(
  phone: string,
  otp: string
): Promise<SendSmsVerifyCodeResponse> {
  const accessKeyId = Deno.env.get("ALIYUN_SMS_ACCESS_KEY_ID");
  const accessKeySecret = Deno.env.get("ALIYUN_SMS_ACCESS_KEY_SECRET");
  // Hardcode sign name to avoid UTF-8 encoding issues with Supabase secrets
  const signName = Deno.env.get("ALIYUN_SMS_SIGN_NAME") ?? "速通互联验证码";
  const templateCode = Deno.env.get("ALIYUN_SMS_TEMPLATE_CODE") ?? "100001";

  if (!accessKeyId || !accessKeySecret) {
    throw new Error(
      "Missing Alibaba Cloud SMS configuration. Required: ALIYUN_SMS_ACCESS_KEY_ID, ALIYUN_SMS_ACCESS_KEY_SECRET"
    );
  }

  // Strip leading + and country code prefix for China numbers
  // dypnsapi expects pure 11-digit number for China (e.g. 13800138000)
  let cleanPhone = phone.startsWith("+") ? phone.slice(1) : phone;
  if (cleanPhone.startsWith("86") && cleanPhone.length === 13) {
    cleanPhone = cleanPhone.slice(2);
  }

  const params: Record<string, string> = {
    AccessKeyId: accessKeyId,
    Action: "SendSmsVerifyCode",
    CodeLength: "6",
    CodeType: "1",
    CountryCode: "86",
    DuplicatePolicy: "1",
    Format: "JSON",
    Interval: "60",
    PhoneNumber: cleanPhone,
    RegionId: "cn-hangzhou",
    SignName: signName,
    SignatureMethod: "HMAC-SHA1",
    SignatureNonce: generateNonce(),
    SignatureVersion: "1.0",
    TemplateCode: templateCode,
    // Pass the OTP generated by Supabase directly (not ##code##)
    TemplateParam: JSON.stringify({ code: otp, min: "5" }),
    Timestamp: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"),
    ValidTime: "300",
    Version: "2017-05-25",
  };

  const signature = generateSignature(params, accessKeySecret);
  params.Signature = signature;

  const body = new URLSearchParams(params).toString();

  const response = await fetch("https://dypnsapi.aliyuncs.com/", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body,
  });

  const responseText = await response.text();
  console.log("Alibaba Cloud raw response:", responseText);
  
  let result: SendSmsVerifyCodeResponse;
  try {
    result = JSON.parse(responseText);
  } catch {
    throw new Error(`Failed to parse response: ${responseText}`);
  }

  if (result.Code !== "OK") {
    const debugInfo = {
      error: result.Code,
      message: result.Message,
      requestId: result.RequestId,
      phoneUsed: cleanPhone,
      signName: signName,
      templateCode: templateCode,
      templateParam: params.TemplateParam,
    };
    console.error("Alibaba Cloud SMS Verify error:", JSON.stringify(debugInfo));
    throw new Error(JSON.stringify(debugInfo));
  }

  console.log("SMS sent successfully via SMS Verify Service:", {
    requestId: result.RequestId,
    bizId: result.Model?.BizId,
  });

  return result;
}

// ─── Webhook signature verification ─────────────────────────────────────────

function verifyWebhookSignature(
  payload: string,
  signature: string | null,
  secret: string
): boolean {
  if (!signature) return false;

  const hmac = createHmac("sha256", secret);
  hmac.update(payload);
  const expected = hmac.digest("hex");

  // Constant-time comparison
  if (expected.length !== signature.length) return false;
  let diff = 0;
  for (let i = 0; i < expected.length; i++) {
    diff |= expected.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return diff === 0;
}

// ─── Main Handler ────────────────────────────────────────────────────────────

Deno.serve(async (req: Request) => {
  // Only accept POST
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  try {
    const rawBody = await req.text();

    // Optional: verify webhook signature if secret is configured
    const hookSecret = Deno.env.get("SUPABASE_AUTH_HOOK_SECRET");
    if (hookSecret) {
      const signature = req.headers.get("x-supabase-signature");
      if (!verifyWebhookSignature(rawBody, signature, hookSecret)) {
        console.error("Invalid webhook signature");
        return new Response(
          JSON.stringify({ error: "Invalid signature" }),
          {
            status: 401,
            headers: { "Content-Type": "application/json" },
          }
        );
      }
    }

    const payload: SendSmsHookPayload = JSON.parse(rawBody);

    const phone = payload.user?.phone;
    const otp = payload.sms?.otp;

    if (!phone || !otp) {
      console.error("Invalid payload: missing phone or otp", payload);
      return new Response(
        JSON.stringify({ error: "Missing phone or otp in payload" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    console.log(`Sending OTP to ${phone.slice(0, -4)}****`);

    await sendAliyunSmsVerifyCode(phone, otp);

    // Return success to GoTrue
    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("send-sms error:", error);

    const message =
      error instanceof Error ? error.message : "Unknown error";

    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
});
