-- Migration: Add feedback table
-- Date: 2026-01-03

CREATE TABLE IF NOT EXISTS "public"."feedback" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
    "content" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."feedback" OWNER TO "postgres";

-- RLS
ALTER TABLE "public"."feedback" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own feedback
CREATE POLICY "Users can insert their own feedback" ON "public"."feedback"
FOR INSERT WITH CHECK ((select auth.uid()) = user_id OR user_id IS NULL);

-- Policy: Users can view their own feedback
CREATE POLICY "Users can view their own feedback" ON "public"."feedback"
FOR SELECT USING ((select auth.uid()) = user_id);

-- Policy: Operators can view all feedback
CREATE POLICY "Operators can view all feedback" ON "public"."feedback"
FOR SELECT USING (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'operator');

-- Index for user_id queries
CREATE INDEX "idx_feedback_user_id" ON "public"."feedback" ("user_id");

-- Index for created_at queries (for sorting)
CREATE INDEX "idx_feedback_created_at" ON "public"."feedback" ("created_at");

-- GIN index for jsonb content queries
CREATE INDEX "idx_feedback_content" ON "public"."feedback" USING gin ("content");

